In [3]:
import numpy as np
# 1
arr = np.full((3,3), True)
print(f'Câu 1:\n{arr}\n')

Câu 1:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]



In [4]:
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print(f"Câu 2:\n{arr_2D}\n")

Câu 2:
[[2 1 0]
 [5 4 3]
 [8 7 6]]



In [5]:
arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print(f"Câu 3:\n{arr_2D}\n")

Câu 3:
[[5 4 3]
 [2 1 0]
 [8 7 6]]



In [6]:
arr_2D = arr_2D[::-1]
print(f"Câu 4:\n{arr_2D}\n")

Câu 4:
[[8 7 6]
 [2 1 0]
 [5 4 3]]



In [7]:
arr_2D = arr_2D[:, ::-1]
print(f"Câu 5:\n{arr_2D}\n")

Câu 5:
[[6 7 8]
 [0 1 2]
 [3 4 5]]



In [8]:
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
has_nan = np.isnan(arr_2D_null).any()
print(f"Câu 6: {'Có' if has_nan else 'Không'} có giá trị rỗng trong mảng.\n")

Câu 6: Có có giá trị rỗng trong mảng.



In [9]:
arr_2D_null[np.isnan(arr_2D_null)] = 0
print(f"Câu 7:\n{arr_2D_null}\n")

Câu 7:
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]

